[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme.git"
    refreshPeriod = "168h"
[".local/share/fcitx5/rime"]
    type = "git-repo"
    url = "https://github.com/Mintimate/oh-my-rime.git"
    refreshPeriod = "999999h"
